### PR TITLE
Added config options for ore generation

### PR DESCRIPTION
**Pull request by SunshineHunter**
This adds config options for the Fossils, Permafrost and Volcanic Rock to generate. I made a request on MCF, but it seems to be simplier to make it myself ;) Reason for this pull request: Ability to configure the generation with CoFH Core.

WARNING: I didn't test/build it! I made this in some minutes in a text editor!

### CODE REVIEW

**Comment by iLexiconn** [comment]
Can one of the admins verify this patch?

**Comment by iLexiconn** [comment]
Can one of the admins verify this patch?

**Comment by iLexiconn** [comment]
Thanks :)

**Comment by SunshineHunter** [comment]
No problem! Glad that this will be implemented.

**Pull request merged**
